on:
  repository_dispatch:
    types: gradle-wrapper
  push:
    branches:
      - master
    paths:
      - 'gradle/**'
  pull_request:
    branches:
      - master
    paths:
      - 'gradle/**'
name: Validated Gradlew
jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1